name: Update Crowdin Sources / Translations
on: workflow_call

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: crowdin/github-action@v1.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
        with:
          upload_sources: true
          download_translations: true
          push_translations: true
          localization_branch_name: master
          create_pull_request: false
          download_translations_args: --all
